In [1]:
import spacy
import pandas as pd

In [2]:
nlp = spacy.load("en_core_web_sm")

In [3]:
emma_ja = "Emma Woodhouse, handsome, clever, and rich, with a comfortable home and happy disposition, seemed to unite some of the best blessings of existence; and had lived nearly twenty-one years in the world with very little to distress or vex her."
print(emma_ja)

Emma Woodhouse, handsome, clever, and rich, with a comfortable home and happy disposition, seemed to unite some of the best blessings of existence; and had lived nearly twenty-one years in the world with very little to distress or vex her.

In [4]:
spacy_doc = nlp(emma_ja)

In [5]:
pos_df = pd.DataFrame(columns=['token', 'pos_tag'])

In [6]:
for token in spacy_doc:
    pos_df = pd.concat([pos_df, pd.DataFrame.from_records([{'token': token.text, 'pos_tag': token.pos_}])], ignore_index=True)

In [7]:
pos_df.head(15)

          token pos_tag
0          Emma   PROPN
1     Woodhouse   PROPN
2             ,   PUNCT
3      handsome     ADJ
4             ,   PUNCT
5        clever     ADJ
6             ,   PUNCT
7           and   CCONJ
8          rich     ADJ
9             ,   PUNCT
10         with     ADP
11            a     DET
12  comfortable     ADJ
13         home    NOUN
14          and   CCONJ

In [8]:
pos_df_counts = pos_df.groupby(['token', 'pos_tag']).size().reset_index(name='counts').sort_values(by='counts', ascending=False)

In [9]:
pos_df_counts.head(10)

     token pos_tag  counts
0        ,   PUNCT       5
7      and   CCONJ       3
24      of     ADP       2
31      to    PART       2
30     the     DET       2
36    with     ADP       2
34    very     ADV       1
33   unite    VERB       1
35     vex    VERB       1
32  twenty     NUM       1

In [10]:
pos_def_poscounts = pos_df_counts.groupby(['pos_tag'])['token'].count().sort_values(ascending=False)

In [11]:
pos_def_poscounts.head(10)

pos_tag
ADJ      7
NOUN     7
PUNCT    4
VERB     4
ADP      3
ADV      2
CCONJ    2
DET      2
NUM      2
PRON     2
Name: token, dtype: int64

In [15]:
nouns = pos_df_counts[pos_df_counts.pos_tag == 'NOUN'][:10]
nouns

          token pos_tag  counts
37        world    NOUN       1
19         home    NOUN       1
9     blessings    NOUN       1
12  disposition    NOUN       1
13     distress    NOUN       1
14    existence    NOUN       1
38        years    NOUN       1